# Generated by Django 6.0.6 on 2026-06-10 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
