# Generated by Django 6.0.6 on 2026-06-10 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_medicine_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='company',
        ),
    ]
