# Generated by Django 6.0.6 on 2026-06-12 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agency_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
