# Generated by Django 6.0.6 on 2026-07-10 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_address_user_gsitn_no_user_pan_no_user_pincode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='parent_seller',
            field=models.ForeignKey(blank=True, help_text='Agar ye ek staff sub-account hai, toh iska Admin/Owner kaun hai.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='staff_role',
            field=models.CharField(blank=True, choices=[('order_manager', 'Order Manager (Pack & Update Orders)'), ('inventory_manager', 'Inventory Manager (Add/Edit Medicines)'), ('full_access', 'Full Access (Orders + Inventory)')], max_length=20, null=True),
        ),
    ]
