# Generated by Django 6.0.6 on 2026-07-23 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_parent_seller_user_staff_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_dismissed_welcome_offer',
            field=models.BooleanField(default=False),
        ),
    ]
