# Generated by Django 6.0.6 on 2026-07-06 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumPlacementPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Top 6 Premium Partner', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=999.0, max_digits=10)),
                ('duration_days', models.IntegerField(default=30, help_text='Duration for Top 6 placement (e.g., 30 days)')),
            ],
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='is_premium_listing',
        ),
        migrations.CreateModel(
            name='PremiumPlacementSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.premiumplacementplan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='premium_placement', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
