# Generated by Django 6.0.6 on 2026-07-06 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_premiumplacementplan_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='can_export_data',
            field=models.BooleanField(default=False, help_text='Allow exporting orders to Excel/CSV?'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='has_analytics_dashboard',
            field=models.BooleanField(default=False, help_text='Provide detailed sales & views analytics?'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='has_custom_domain',
            field=models.BooleanField(default=False, help_text='Allow custom subdomain masking?'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='has_stock_alerts',
            field=models.BooleanField(default=False, help_text='Send automated low-stock alerts?'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_staff_accounts',
            field=models.IntegerField(default=0, help_text='How many sub-users can the seller create? (0 for none)'),
        ),
        migrations.CreateModel(
            name='StoreProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fssai_license_number', models.CharField(blank=True, max_length=50, null=True)),
                ('fssai_document', models.FileField(blank=True, null=True, upload_to='seller_documents/')),
                ('is_verified', models.BooleanField(default=False, help_text='Admin will check this to give the Blue Tick')),
                ('custom_subdomain', models.CharField(blank=True, help_text="e.g., 'vermapharmacy' for vermapharmacy.meditrack.com", max_length=50, null=True, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
