# Generated by Django 6.0.6 on 2026-07-23 04:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_alter_usersubscription_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeprofile',
            name='custom_subdomain',
            field=models.CharField(blank=True, help_text="e.g., 'vermapharmacy' for vermapharmacy.DawaiSetu.com", max_length=50, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='PromoOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'First-Time Seller Offer'", max_length=100)),
                ('discount_percent', models.PositiveIntegerField(help_text='e.g. 30 for 30% off')),
                ('first_time_only', models.BooleanField(default=False, help_text='Only show to sellers who never purchased any plan')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(blank=True, help_text='Leave blank for expiry', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('plans', models.ManyToManyField(blank=True, help_text='Leave empty to apply to All plans', to='subscriptions.subscriptionplan')),
            ],
        ),
    ]
