# Generated by Django 6.0.6 on 2026-07-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_alter_storeprofile_custom_subdomain_promooffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='storeprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='storeprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='storeprofile',
            name='store_address',
            field=models.TextField(blank=True, help_text='Full address of the medical store', null=True),
        ),
    ]
