# Generated by Django 6.0.6 on 2026-07-24 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_storeprofile_city_storeprofile_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='storeprofile',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='storeprofile',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='storeprofile',
            name='store_address',
        ),
    ]
