# Generated by Django 6.0.6 on 2026-06-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='seller_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
