# Generated by Django 6.0.6 on 2026-07-18 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_customer_hidden_order_seller_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='refill_after_days',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='refill_reminder_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='refill_reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
